
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'preventa_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +transient: false
  my_new_project:
    # Applies to all files under models/example/

    staging:
      +materialized: view
      +database: |  
        {%- if  target.name == 'user_dev' -%} demo_silver_db
        {%- elif target.name == 'ci' -%} demo_silver_db 
        {%- elif target.name == 'pro'-%} pro_silver_db  
        {%- else -%} {{target.database}}_silver_db
        {%- endif -%}
      google_sheets:
        +schema: google_sheets
      sql_server_dbo:
        +schema: sql_server_dbo
      seeds:
        +schema: seeds

      
    marts:
      +materialized: table
      +database: |  
        {%- if  target.name == 'user_dev' -%} demo_gold_db  
        {%- elif target.name == 'ci' -%} demo_gold_db 
        {%- elif target.name == 'pro'-%} pro_gold_db
        {%- else -%} {{target.database}}_gold_db
        {%- endif -%}
      core:
        +schema: core
                  
        
snapshots:
  +sql_header: "alter session set timezone = 'Europe/Madrid';alter session set week_start = 7;"
  +transient: false
  +target_database: |  
        {%- if  target.name == 'user_dev' -%} demo_silver_db
        {%- elif target.name == 'ci' -%} demo_silver_db 
        {%- elif target.name == 'pro'-%} pro_silver_db  
        {%- else -%} {{target.database}}_silver_db
        {%- endif -%}
  +target_schema: snapshots